### ISSUE TITLE
[Bug] Commands fail on Windows due to single quotes

### ISSUE THREAD

**Issue by boyuanx** [windranger-io/windranger-solidity-template#108]
## Bug Description

Various build and formatting commands fail on Windows (using git-bash) due to single quotes

## Expected Behaviour

Code that compiles and builds on macOS does the same on Windows

## Current Behaviour

`npm run format` and `npm run test` fails. 

For example, the error message for `npm run format`:
`[error] No files matching the pattern were found: "'**/*.ts'".`

## Steps to Reproduce
1. Clone this repo
2. Run `npm run format`

## Additional Information

Escaping commands to double quotes in `package.json` seems to fix the issues on Windows.

**Comment by CjHare** [comment]
@boyuanx thanks for raising the bug! ...and congratulations on being the first to try this on Windows 🎉 

**question:** were you running the Terminal, PowerShell or WLS?

**Comment by CjHare** [comment]
Working on fix, testing verifying  on
- Windows Powershell 5.1.22000
- Windows Terminal 1.11,341.0
- MacOszsh 5.8 (x86_64-apple-darwin20.1.0)
