### ISSUE TITLE
[Bug] Constant within struct - solc / solhint conflict

### ISSUE THREAD

**Issue by aodhgan** [windranger-io/windranger-solidity-template#139]
## Bug Description

Solhint is not allowing the definition of constant size arrays within a struct, giving ` error  Function order is incorrect, struct definition can not go after state variable declaration (line 15)  ordering`

Consider: 
```
   uint256 internal constant _CONST_SIZE = 5;
    struct StructWithConstantSizeArray{
        uint256[_CONST_SIZE] array;  
    }
```
which is valid solidity, but Solhint rejects

While 
```

    struct StructWithConstantSizeArray{
        uint256[_CONST_SIZE] array;  
    }
   uint256 internal constant _CONST_SIZE = 5;
```
solc rejects (maybe as it cannot see ` _CONST_SIZE` yet). 
Non magic number fixed size arrays are good for packed gas optimised structs. Is there a workaround such as place in a library or change the solhint rules for constants?

@CjHare

**Comment by CjHare** [comment]
@aodhgan can you place the constant definition inside the struct?

**Comment by aodhgan** [comment]
Doesnt seem like you can!

**Comment by CjHare** [comment]
Interesting, although expected 😞

**Comment by CjHare** [comment]
Well then, are the SolHint rule is generally sensible, there's are two clear choices for this specific case:
1. An ignore statement
2. Use a library to store the constant

I'd lean towards using a library, as it splits up contracts into smaller pieces, but wdyt?

**Comment by CjHare** [comment]
Workaround applied. 👍
