### ISSUE TITLE
Enable releases to allow importing this as a dependency into project

### ISSUE THREAD

**Issue by shahankhatch** [windranger-io/windranger-solidity-template#18]
Using github templates solves the immediate challenge of bootstrapping a good dev setup for smart contract development. 
However, due to the divergence of github histories when using templates that are updated, there's an issue of how we update and version repos generated from the template, as well as versioning the pipeline itself.

To resolve, let's consider an approach that brings the functionality of this repo to an downstream smart contract repo. 

A couple of potential approaches that may be useful in such an integration:
1. thinking of this repo as a git-submodule 
2. allowing this repo to be added a dependency in `package.json`
3. if needed, add a `prepare` lifecycle build script to this repo so that this git submodule is built properly when `npm install` is run on the downstream repo

**Comment by CjHare** [comment]
Unfortunately GitHub templates provide no mechanism for an auto-update PR being raised all projects that were bootstrapped using it.

The challenge with morphing the template into dependency will be the lack of support for overriding scripts that JS/TS provide for script and package management.

It may be worthwhile to split the project into two parts, the first a GitHub template then a clump of it into either a git submodule or npm package. Depends on the direction that repo evolves in and purposes it serves 🤔

**Comment by CjHare** [comment]
Walkthrough of using a GitHub repo as a dependency.

https://medium.com/@jonchurch/use-github-branch-as-dependency-in-package-json-5eb609c81f1a

What this does do is mimic the functionality of an Npm release ...but, that is not equivalent to using a project as a template, as the template provides the `package.json`, Github actions and settings, while a dependency does not 😞

**Comment by CjHare** [comment]
The various config files can be moved into a released dependency.

(might want two dependenices, one for the perrDependencies `solidity-dependencies`, the other for config `coding-standards`)

https://eslint.org/docs/user-guide/configuring/configuration-files#extending-configuration-files
