### ISSUE TITLE
[Feature] OZ upgrades package as a dependency

### ISSUE THREAD

**Issue by bitparadigm** [windranger-io/windranger-solidity-template#76]
## Feature Description

I suggest to add https://github.com/OpenZeppelin/openzeppelin-upgrades as dependency to template repo as it will be used for most contracts developed by WindRanger and for most repos. Provides automatic proxy deployments and upgrades management. Can be used in scripts and tests. @CjHare

**Comment by CjHare** [comment]
Yes, after the treasury has the upgrades working & tested (with framework additions) they'll get promoted to the template repo.
